In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

pd.set_option("display.max_columns", None)

In [ ]:
from google.colab import files
uploaded = files.upload()   # a "Choose Files" button appears; select Palo Alto Networks.csv

df = pd.read_csv("Palo Alto Networks.csv")
print(df.shape)             # expect (1470, 31)
df.head()

Saving Palo Alto Networks.csv to Palo Alto Networks (1).csv
(1470, 31)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Yes,11,3,1,0,8,0,1,6,4,0,5
1,49,0,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,No,23,4,4,1,10,3,3,10,7,1,7
2,37,1,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Yes,15,3,2,0,7,3,3,0,0,0,0
3,33,0,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Yes,11,3,3,0,8,3,3,8,7,3,0
4,27,0,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,No,12,3,4,1,6,3,3,2,2,2,2

In [ ]:
df.info()
df.describe().T

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 31 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   int64
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EnvironmentSatisfaction   1470 non-null   int64
 9   Gender                    1470 non-null   object
 10  HourlyRate                1470 non-null   int64
 11  JobInvolvement            1470 non-null   int64
 12  JobLevel                  1470 non-null   int64
 13  JobRole                   1470 non-null   object
 14  JobSatisfaction           1470 non-null   int64
 15  MaritalStatus             1470 non-null   object
 16  MonthlyIncome             1470 non-null   int64
 17  MonthlyRate               1470 non-null   int64
 18  NumCompaniesWorked        1470 non-null   int64
 19  OverTime                  1470 non-null   object
 20  PercentSalaryHike         1470 non-null   int64
 21  PerformanceRating         1470 non-null   int64
 22  RelationshipSatisfaction  1470 non-null   int64
 23  StockOptionLevel          1470 non-null   int64
 24  TotalWorkingYears         1470 non-null   int64
 25  TrainingTimesLastYear     1470 non-null   int64
 26  WorkLifeBalance           1470 non-null   int64
 27  YearsAtCompany            1470 non-null   int64
 28  YearsInCurrentRole        1470 non-null   int64
 29  YearsSinceLastPromotion   1470 non-null   int64
 30  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(24), object(7)
memory usage: 356.1+ KB

,count,mean,std,min,25%,50%,75%,max
Age,1470.0,36.923810,9.135373,18.0,30.0,36.0,43.00,60.0
Attrition,1470.0,0.161224,0.367863,0.0,0.0,0.0,0.00,1.0
DailyRate,1470.0,802.485714,403.509100,102.0,465.0,802.0,1157.00,1499.0
DistanceFromHome,1470.0,9.192517,8.106864,1.0,2.0,7.0,14.00,29.0
Education,1470.0,2.912925,1.024165,1.0,2.0,3.0,4.00,5.0
EnvironmentSatisfaction,1470.0,2.721769,1.093082,1.0,2.0,3.0,4.00,4.0
HourlyRate,1470.0,65.891156,20.329428,30.0,48.0,66.0,83.75,100.0
JobInvolvement,1470.0,2.729932,0.711561,1.0,2.0,3.0,3.00,4.0
JobLevel,1470.0,2.063946,1.106940,1.0,1.0,2.0,3.00,5.0
JobSatisfaction,1470.0,2.728571,1.102846,1.0,2.0,3.0,4.00,4.0
MonthlyIncome,1470.0,6502.931293,4707.956783,1009.0,2911.0,4919.0,8379.00,19999.0
MonthlyRate,1470.0,14313.103401,7117.786044,2094.0,8047.0,14235.5,20461.50,26999.0
NumCompaniesWorked,1470.0,2.693197,2.498009,0.0,1.0,2.0,4.00,9.0
PercentSalaryHike,1470.0,15.209524,3.659938,11.0,12.0,14.0,18.00,25.0
PerformanceRating,1470.0,3.153741,0.360824,3.0,3.0,3.0,3.00,4.0
RelationshipSatisfaction,1470.0,2.712245,1.081209,1.0,2.0,3.0,4.00,4.0
StockOptionLevel,1470.0,0.793878,0.852077,0.0,0.0,1.0,1.00,3.0
TotalWorkingYears,1470.0,11.279592,7.780782,0.0,6.0,10.0,15.00,40.0
TrainingTimesLastYear,1470.0,2.799320,1.289271,0.0,2.0,3.0,3.00,6.0
WorkLifeBalance,1470.0,2.761224,0.706476,1.0,2.0,3.0,3.00,4.0
YearsAtCompany,1470.0,7.008163,6.126525,0.0,3.0,5.0,9.00,40.0
YearsInCurrentRole,1470.0,4.229252,3.623137,0.0,2.0,3.0,7.00,18.0
YearsSinceLastPromotion,1470.0,2.187755,3.222430,0.0,0.0,1.0,3.00,15.0
YearsWithCurrManager,1470.0,4.123129,3.568136,0.0,2.0,3.0,7.00,17.0

In [ ]:
print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())
print("\nAttrition values:\n", df["Attrition"].value_counts(dropna=False))

print("\n--- Categorical columns ---")
for col in ["BusinessTravel", "Department", "EducationField",
            "Gender", "JobRole", "MaritalStatus", "OverTime"]:
    print(col, "->", df[col].unique())

print("\n--- Ordinal range checks ---")
scales = {"Education": range(1,6), "EnvironmentSatisfaction": range(1,5),
          "JobSatisfaction": range(1,5), "JobInvolvement": range(1,5),
          "RelationshipSatisfaction": range(1,5), "WorkLifeBalance": range(1,5)}
for col, valid in scales.items():
    print(col, "out-of-range:", (~df[col].isin(valid)).sum())

print("\n--- Logical consistency ---")
print("YearsAtCompany > TotalWorkingYears:", (df.YearsAtCompany > df.TotalWorkingYears).sum())
print("YearsInCurrentRole > YearsAtCompany:", (df.YearsInCurrentRole > df.YearsAtCompany).sum())
print("YearsWiDthCurrManager > YearsAtCompany:", (df.YearsWithCurrManager > df.YearsAtCompany).sum())
print("Age - TotalWorkingYears < 14:", ((df.Age - df.TotalWorkingYears) < 14).sum())

Missing values: 0
Duplicate rows: 0

Attrition values:
 Attrition
0    1233
1     237
Name: count, dtype: int64

--- Categorical columns ---
BusinessTravel -> ['Travel_Rarely' 'Travel_Frequently' 'Non-Travel']
Department -> ['Sales' 'Research & Development' 'Human Resources']
EducationField -> ['Life Sciences' 'Other' 'Medical' 'Marketing' 'Technical Degree'
 'Human Resources']
Gender -> ['Female' 'Male']
JobRole -> ['Sales Executive' 'Research Scientist' 'Laboratory Technician'
 'Manufacturing Director' 'Healthcare Representative' 'Manager'
 'Sales Representative' 'Research Director' 'Human Resources']
MaritalStatus -> ['Single' 'Married' 'Divorced']
OverTime -> ['Yes' 'No']

--- Ordinal range checks ---
Education out-of-range: 0
EnvironmentSatisfaction out-of-range: 0
JobSatisfaction out-of-range: 0
JobInvolvement out-of-range: 0
RelationshipSatisfaction out-of-range: 0
WorkLifeBalance out-of-range: 0

--- Logical consistency ---
YearsAtCompany > TotalWorkingYears: 0
YearsInCurrentRole > YearsAtCompany: 0
YearsWithCurrManager > YearsAtCompany: 0
Age - TotalWorkingYears < 14: 0

In [ ]:
rows_before = len(df)

# Strip whitespace in text columns
for c in df.select_dtypes(include="object").columns:
    df[c] = df[c].str.strip()

# Drop duplicates and rows missing key fields
df = df.drop_duplicates()
df = df.dropna(subset=["Attrition", "Department", "JobRole"])

# Readable labels for charts and the dashboard
df["AttritionLabel"] = df["Attrition"].map({0: "Retained", 1: "Exited"})
df["EducationLabel"] = df["Education"].map(
    {1: "Below College", 2: "College", 3: "Bachelor", 4: "Master", 5: "Doctor"})

print("Rows before:", rows_before, "| after:", len(df))

Rows before: 1470 | after: 1470

In [ ]:
print(df["AttritionLabel"].value_counts())
print(df["Attrition"].mean().round(4) * 100, "% overall attrition")
df.head()

AttritionLabel
Retained    1233
Exited       237
Name: count, dtype: int64
16.12 % overall attrition

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,AttritionLabel,EducationLabel
0,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Yes,11,3,1,0,8,0,1,6,4,0,5,Exited,College
1,49,0,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,No,23,4,4,1,10,3,3,10,7,1,7,Retained,Below College
2,37,1,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Yes,15,3,2,0,7,3,3,0,0,0,0,Exited,College
3,33,0,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Yes,11,3,3,0,8,3,3,8,7,3,0,Retained,Master
4,27,0,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,No,12,3,4,1,6,3,3,2,2,2,2,Retained,Below College

In [ ]:
df.to_csv("cleaned_attrition.csv", index=False)
files.download("cleaned_attrition.csv")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
df.to_csv('/content/drive/MyDrive/cleaned_attrition.csv', index=False)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df["BusinessTravel"] = df["BusinessTravel"].replace({
    "Travel_Rarely": "Travel Rarely",
    "Travel_Frequently": "Travel Frequently"})

df["Department"] = df["Department"].replace({
    "Research & Development": "R&D",
    "Human Resources": "HR"})

print(df["BusinessTravel"].unique())
print(df["Department"].unique())

['Travel Rarely' 'Travel Frequently' 'Non-Travel']
['Sales' 'R&D' 'HR']

In [ ]:
from statsmodels.stats.proportion import proportion_confint

total    = len(df)
exited   = int(df["Attrition"].sum())
retained = total - exited
rate     = exited / total * 100

low, high = proportion_confint(exited, total, method="wilson")

print(f"Total employees : {total}")
print(f"Retained        : {retained} ({retained/total*100:.2f}%)")
print(f"Exited          : {exited} ({rate:.2f}%)")
print(f"Overall attrition rate: {rate:.2f}%")
print(f"95% confidence interval: {low*100:.2f}% to {high*100:.2f}%")
print(f"Retained per 1 exit: {retained/exited:.1f}")

Total employees : 1470
Retained        : 1233 (83.88%)
Exited          : 237 (16.12%)
Overall attrition rate: 16.12%
95% confidence interval: 14.33% to 18.09%
Retained per 1 exit: 5.2

In [ ]:
summary = df["AttritionLabel"].value_counts().reset_index()
summary.columns = ["Status", "Employees"]

fig = px.pie(summary, names="Status", values="Employees", hole=0.5,
             color="Status",
             color_discrete_map={"Retained": "#2E86AB", "Exited": "#E4572E"},
             title=f"Retained vs Exited Employees (Attrition = {rate:.1f}%)")
fig.update_traces(textinfo="label+percent+value")
fig.show()

fig2 = px.bar(summary, x="Status", y="Employees", text="Employees",
              color="Status",
              color_discrete_map={"Retained": "#2E86AB", "Exited": "#E4572E"},
              title="Employee Count by Attrition Status")
fig2.show()

In [ ]:
df.to_csv("cleaned_attrition.csv", index=False)
files.download("cleaned_attrition.csv")

In [ ]:
dept = (df.groupby("Department")
          .agg(Employees=("Attrition", "size"),
               Exited=("Attrition", "sum"))
          .assign(AttritionRate=lambda x: (x.Exited / x.Employees * 100).round(2))
          .sort_values("AttritionRate", ascending=False)
          .reset_index())

dept["vs_Overall_pp"] = (dept.AttritionRate - rate).round(2)   # percentage points above/below 16.12%
dept["Share_of_All_Exits_%"] = (dept.Exited / exited * 100).round(2)
dept

,Department,Employees,Exited,AttritionRate,vs_Overall_pp,Share_of_All_Exits_%
0,Sales,446,92,20.63,4.51,38.82
1,HR,63,12,19.05,2.93,5.06
2,R&D,961,133,13.84,-2.28,56.12

In [ ]:
fig = px.bar(dept, x="Department", y="AttritionRate", text="AttritionRate",
             color="AttritionRate", color_continuous_scale="Reds",
             title="Attrition Rate by Department (%)")
fig.add_hline(y=rate, line_dash="dash", line_color="black",
              annotation_text=f"Overall {rate:.1f}%")
fig.update_traces(texttemplate="%{text:.1f}%", textposition="outside")
fig.show()

In [ ]:
role = (df.groupby("JobRole")
          .agg(Employees=("Attrition", "size"),
               Exited=("Attrition", "sum"))
          .assign(AttritionRate=lambda x: (x.Exited / x.Employees * 100).round(2))
          .sort_values("AttritionRate", ascending=False)
          .reset_index())

role["vs_Overall_pp"] = (role.AttritionRate - rate).round(2)
role["Share_of_All_Exits_%"] = (role.Exited / exited * 100).round(2)
role

,JobRole,Employees,Exited,AttritionRate,vs_Overall_pp,Share_of_All_Exits_%
0,Sales Representative,83,33,39.76,23.64,13.92
1,Laboratory Technician,259,62,23.94,7.82,26.16
2,Human Resources,52,12,23.08,6.96,5.06
3,Sales Executive,326,57,17.48,1.36,24.05
4,Research Scientist,292,47,16.10,-0.02,19.83
5,Manufacturing Director,145,10,6.90,-9.22,4.22
6,Healthcare Representative,131,9,6.87,-9.25,3.80
7,Manager,102,5,4.90,-11.22,2.11
8,Research Director,80,2,2.50,-13.62,0.84

In [ ]:
# Rate: which roles are riskiest relative to their size
fig = px.bar(role.sort_values("AttritionRate"), x="AttritionRate", y="JobRole",
             orientation="h", text="AttritionRate", color="AttritionRate",
             color_continuous_scale="Reds", title="Attrition Rate by Job Role (%)")
fig.add_vline(x=rate, line_dash="dash", line_color="black",
              annotation_text=f"Overall {rate:.1f}%")
fig.update_traces(texttemplate="%{text:.1f}%", textposition="outside")
fig.show()

# Exit frequency: which roles contribute the most people leaving
fig2 = px.bar(role.sort_values("Exited"), x="Exited", y="JobRole",
              orientation="h", text="Exited", color="Exited",
              color_continuous_scale="Oranges",
              title="Number of Exits by Job Role")
fig2.show()

In [ ]:
heat = (df.pivot_table(index="JobRole", columns="Department",
                       values="Attrition", aggfunc="mean") * 100).round(1)

fig = px.imshow(heat, text_auto=True, color_continuous_scale="Reds",
                aspect="auto",
                title="Attrition Rate (%) by Job Role and Department")
fig.show()

In [ ]:
from scipy.stats import chi2_contingency

ct_dept = pd.crosstab(df["Department"], df["Attrition"])
chi2, p, _, _ = chi2_contingency(ct_dept)
print(f"Department vs Attrition: chi2={chi2:.2f}, p-value={p:.4f}")

ct_role = pd.crosstab(df["JobRole"], df["Attrition"])
chi2, p, _, _ = chi2_contingency(ct_role)
print(f"Job Role vs Attrition:   chi2={chi2:.2f}, p-value={p:.4f}")

Department vs Attrition: chi2=10.80, p-value=0.0045
Job Role vs Attrition:   chi2=86.19, p-value=0.0000

In [ ]:
df.to_csv("cleaned_attrition.csv", index=False)
files.download("cleaned_attrition.csv")

In [ ]:
def attr_table(col, order=None):
    t = (df.groupby(col, observed=True)
           .agg(Employees=("Attrition", "size"), Exited=("Attrition", "sum"))
           .assign(AttritionRate=lambda x: (x.Exited / x.Employees * 100).round(2))
           .reset_index())
    t["vs_Overall_pp"] = (t.AttritionRate - rate).round(2)
    if order:
        t[col] = pd.Categorical(t[col], categories=order, ordered=True)
        t = t.sort_values(col)
    else:
        t = t.sort_values("AttritionRate", ascending=False)
    return t.reset_index(drop=True)

def rate_chart(t, col, title):
    fig = px.bar(t, x=col, y="AttritionRate", text="AttritionRate",
                 color="AttritionRate", color_continuous_scale="Reds", title=title)
    fig.add_hline(y=rate, line_dash="dash", line_color="black",
                  annotation_text=f"Overall {rate:.1f}%")
    fig.update_traces(texttemplate="%{text:.1f}%", textposition="outside")
    fig.show()

In [ ]:
df["AgeGroup"] = pd.cut(df["Age"], bins=[17, 25, 35, 45, 55, 100],
                        labels=["18-25", "26-35", "36-45", "46-55", "56+"])

age = attr_table("AgeGroup", order=["18-25", "26-35", "36-45", "46-55", "56+"])
display(age)
rate_chart(age, "AgeGroup", "Attrition Rate by Age Group (%)")

  AgeGroup  Employees  Exited  AttritionRate  vs_Overall_pp
0    18-25        123      44          35.77          19.65
1    26-35        606     116          19.14           3.02
2    36-45        468      43           9.19          -6.93
3    46-55        226      26          11.50          -4.62
4      56+         47       8          17.02           0.90

In [ ]:
gender = attr_table("Gender")
display(gender)
rate_chart(gender, "Gender", "Attrition Rate by Gender (%)")

marital = attr_table("MaritalStatus")
display(marital)
rate_chart(marital, "MaritalStatus", "Attrition Rate by Marital Status (%)")

   Gender  Employees  Exited  AttritionRate  vs_Overall_pp
0    Male        882     150          17.01           0.89
1  Female        588      87          14.80          -1.32

  MaritalStatus  Employees  Exited  AttritionRate  vs_Overall_pp
0        Single        470     120          25.53           9.41
1       Married        673      84          12.48          -3.64
2      Divorced        327      33          10.09          -6.03

In [ ]:
edu_order = ["Below College", "College", "Bachelor", "Master", "Doctor"]
edu = attr_table("EducationLabel", order=edu_order)
display(edu)
rate_chart(edu, "EducationLabel", "Attrition Rate by Education Level (%)")

field = attr_table("EducationField")
display(field)
rate_chart(field, "EducationField", "Attrition Rate by Education Field (%)")

  EducationLabel  Employees  Exited  AttritionRate  vs_Overall_pp
0  Below College        170      31          18.24           2.12
1        College        282      44          15.60          -0.52
2       Bachelor        572      99          17.31           1.19
3         Master        398      58          14.57          -1.55
4         Doctor         48       5          10.42          -5.70

     EducationField  Employees  Exited  AttritionRate  vs_Overall_pp
0   Human Resources         27       7          25.93           9.81
1  Technical Degree        132      32          24.24           8.12
2         Marketing        159      35          22.01           5.89
3     Life Sciences        606      89          14.69          -1.43
4           Medical        464      63          13.58          -2.54
5             Other         82      11          13.41          -2.71

In [ ]:
heat = (df.pivot_table(index="AgeGroup", columns="MaritalStatus",
                       values="Attrition", aggfunc="mean", observed=True) * 100).round(1)

fig = px.imshow(heat, text_auto=True, color_continuous_scale="Reds", aspect="auto",
                title="Attrition Rate (%) by Age Group and Marital Status")
fig.show()

In [ ]:
from scipy.stats import chi2_contingency

for col in ["AgeGroup", "Gender", "MaritalStatus", "EducationLabel", "EducationField"]:
    chi2, p, _, _ = chi2_contingency(pd.crosstab(df[col], df["Attrition"]))
    verdict = "significant" if p < 0.05 else "not significant"
    print(f"{col:15s} chi2={chi2:6.2f}  p={p:.4f}  -> {verdict}")

AgeGroup        chi2= 59.44  p=0.0000  -> significant
Gender          chi2=  1.12  p=0.2906  -> not significant
MaritalStatus   chi2= 46.16  p=0.0000  -> significant
EducationLabel  chi2=  3.07  p=0.5455  -> not significant
EducationField  chi2= 16.02  p=0.0068  -> significant

In [ ]:
df.to_csv("cleaned_attrition.csv", index=False)
files.download("cleaned_attrition.csv")

In [ ]:
df["TenureBand"] = pd.cut(df["YearsAtCompany"],
                          bins=[-1, 1, 2, 5, 10, 20, 100],
                          labels=["0-1", "2", "3-5", "6-10", "11-20", "21+"])

tenure_order = ["0-1", "2", "3-5", "6-10", "11-20", "21+"]
tenure = attr_table("TenureBand", order=tenure_order)
display(tenure)
rate_chart(tenure, "TenureBand", "Attrition Rate by Tenure Band (years at company)")

  TenureBand  Employees  Exited  AttritionRate  vs_Overall_pp
0        0-1        215      75          34.88          18.76
1          2        127      27          21.26           5.14
2        3-5        434      60          13.82          -2.30
3       6-10        448      55          12.28          -3.84
4      11-20        180      12           6.67          -9.45
5        21+         66       8          12.12          -4.00

In [ ]:
by_year = (df.groupby("YearsAtCompany")
             .agg(Employees=("Attrition", "size"), Exited=("Attrition", "sum"))
             .assign(AttritionRate=lambda x: x.Exited / x.Employees * 100)
             .reset_index())
by_year = by_year[by_year.YearsAtCompany <= 20]

fig = px.line(by_year, x="YearsAtCompany", y="AttritionRate", markers=True,
              hover_data=["Employees", "Exited"],
              title="Attrition Rate by Exact Years at Company (0-20)")
fig.add_hline(y=rate, line_dash="dash", line_color="black",
              annotation_text=f"Overall {rate:.1f}%")
fig.show()

In [ ]:
df["CareerStage"] = pd.cut(df["TotalWorkingYears"],
                           bins=[-1, 5, 15, 100],
                           labels=["Early (0-5 yrs)", "Mid (6-15 yrs)", "Senior (16+ yrs)"])

stage_order = ["Early (0-5 yrs)", "Mid (6-15 yrs)", "Senior (16+ yrs)"]
stage = attr_table("CareerStage", order=stage_order)
stage["Share_of_All_Exits_%"] = (stage.Exited / exited * 100).round(2)
display(stage)
rate_chart(stage, "CareerStage", "Attrition Rate by Career Stage (%)")

# Job level as a second view of seniority
level = attr_table("JobLevel", order=[1, 2, 3, 4, 5])
display(level)
rate_chart(level, "JobLevel", "Attrition Rate by Job Level (%)")

,CareerStage,Employees,Exited,AttritionRate,vs_Overall_pp,Share_of_All_Exits_%
0,Early (0-5 yrs),316,91,28.80,12.68,38.40
1,Mid (6-15 yrs),798,115,14.41,-1.71,48.52
2,Senior (16+ yrs),356,31,8.71,-7.41,13.08

  JobLevel  Employees  Exited  AttritionRate  vs_Overall_pp
0        1        543     143          26.34          10.22
1        2        534      52           9.74          -6.38
2        3        218      32          14.68          -1.44
3        4        106       5           4.72         -11.40
4        5         69       5           7.25          -8.87

In [ ]:
for x in [1, 2, 3, 5]:
    grp = df[df["YearsAtCompany"] <= x]
    ex  = int(grp["Attrition"].sum())
    print(f"Within first {x} yr(s): {len(grp):4d} employees, {ex:3d} exits, "
          f"rate = {ex/len(grp)*100:5.2f}%, share of all exits = {ex/exited*100:5.2f}%")

early = df[df["YearsAtCompany"] <= 2]
later = df[df["YearsAtCompany"] > 2]
print(f"\nEarly-tenure (<=2 yrs) rate: {early.Attrition.mean()*100:.2f}%")
print(f"Later-tenure  (>2 yrs) rate: {later.Attrition.mean()*100:.2f}%")
print(f"Ratio: {early.Attrition.mean()/later.Attrition.mean():.2f}x")

Within first 1 yr(s):  215 employees,  75 exits, rate = 34.88%, share of all exits = 31.65%
Within first 2 yr(s):  342 employees, 102 exits, rate = 29.82%, share of all exits = 43.04%
Within first 3 yr(s):  470 employees, 122 exits, rate = 25.96%, share of all exits = 51.48%
Within first 5 yr(s):  776 employees, 162 exits, rate = 20.88%, share of all exits = 68.35%

Early-tenure (<=2 yrs) rate: 29.82%
Later-tenure  (>2 yrs) rate: 11.97%
Ratio: 2.49x

In [ ]:
df["PromotionGap"] = pd.cut(df["YearsSinceLastPromotion"],
                            bins=[-1, 0, 2, 5, 100],
                            labels=["Promoted this year", "1-2 yrs", "3-5 yrs", "6+ yrs"])

promo_order = ["Promoted this year", "1-2 yrs", "3-5 yrs", "6+ yrs"]
promo = attr_table("PromotionGap", order=promo_order)
display(promo)
rate_chart(promo, "PromotionGap", "Attrition Rate by Years Since Last Promotion (%)")

         PromotionGap  Employees  Exited  AttritionRate  vs_Overall_pp
0  Promoted this year        581     110          18.93           2.81
1             1-2 yrs        516      76          14.73          -1.39
2             3-5 yrs        158      16          10.13          -5.99
3              6+ yrs        215      35          16.28           0.16

In [ ]:
heat = (df.pivot_table(index="TenureBand", columns="Department",
                       values="Attrition", aggfunc="mean", observed=True) * 100).round(1)

fig = px.imshow(heat, text_auto=True, color_continuous_scale="Reds", aspect="auto",
                title="Attrition Rate (%) by Tenure Band and Department")
fig.show()

In [ ]:
for col in ["TenureBand", "CareerStage", "JobLevel", "PromotionGap"]:
    chi2, p, _, _ = chi2_contingency(pd.crosstab(df[col], df["Attrition"]))
    verdict = "significant" if p < 0.05 else "not significant"
    print(f"{col:13s} chi2={chi2:6.2f}  p={p:.4f}  -> {verdict}")

TenureBand    chi2= 77.72  p=0.0000  -> significant
CareerStage   chi2= 53.74  p=0.0000  -> significant
JobLevel      chi2= 72.53  p=0.0000  -> significant
PromotionGap  chi2=  8.34  p=0.0395  -> significant

In [ ]:
df.to_csv("cleaned_attrition.csv", index=False)
files.download("cleaned_attrition.csv")

In [ ]:
for name, t in [("AGE", age), ("MARITAL", marital), ("EDU FIELD", field),
                ("TENURE", tenure), ("STAGE", stage), ("LEVEL", level), ("PROMO", promo)]:
    print(f"\n--- {name} ---")
    print(t.to_string(index=False))

--- AGE ---
AgeGroup  Employees  Exited  AttritionRate  vs_Overall_pp
   18-25        123      44          35.77          19.65
   26-35        606     116          19.14           3.02
   36-45        468      43           9.19          -6.93
   46-55        226      26          11.50          -4.62
     56+         47       8          17.02           0.90

--- MARITAL ---
MaritalStatus  Employees  Exited  AttritionRate  vs_Overall_pp
       Single        470     120          25.53           9.41
      Married        673      84          12.48          -3.64
     Divorced        327      33          10.09          -6.03

--- EDU FIELD ---
  EducationField  Employees  Exited  AttritionRate  vs_Overall_pp
 Human Resources         27       7          25.93           9.81
Technical Degree        132      32          24.24           8.12
       Marketing        159      35          22.01           5.89
   Life Sciences        606      89          14.69          -1.43
         Medical        464      63          13.58          -2.54
           Other         82      11          13.41          -2.71

--- TENURE ---
TenureBand  Employees  Exited  AttritionRate  vs_Overall_pp
       0-1        215      75          34.88          18.76
         2        127      27          21.26           5.14
       3-5        434      60          13.82          -2.30
      6-10        448      55          12.28          -3.84
     11-20        180      12           6.67          -9.45
       21+         66       8          12.12          -4.00

--- STAGE ---
     CareerStage  Employees  Exited  AttritionRate  vs_Overall_pp  Share_of_All_Exits_%
 Early (0-5 yrs)        316      91          28.80          12.68                 38.40
  Mid (6-15 yrs)        798     115          14.41          -1.71                 48.52
Senior (16+ yrs)        356      31           8.71          -7.41                 13.08

--- LEVEL ---
JobLevel  Employees  Exited  AttritionRate  vs_Overall_pp
       1        543     143          26.34          10.22
       2        534      52           9.74          -6.38
       3        218      32          14.68          -1.44
       4        106       5           4.72         -11.40
       5         69       5           7.25          -8.87

--- PROMO ---
      PromotionGap  Employees  Exited  AttritionRate  vs_Overall_pp
Promoted this year        581     110          18.93           2.81
           1-2 yrs        516      76          14.73          -1.39
           3-5 yrs        158      16          10.13          -5.99
            6+ yrs        215      35          16.28           0.16

In [ ]:
ot = attr_table("OverTime")
display(ot)
rate_chart(ot, "OverTime", "Attrition Rate: Overtime vs No Overtime (%)")

  OverTime  Employees  Exited  AttritionRate  vs_Overall_pp
0      Yes        416     127          30.53          14.41
1       No       1054     110          10.44          -5.68

In [ ]:
travel_order = ["Non-Travel", "Travel Rarely", "Travel Frequently"]
travel = attr_table("BusinessTravel", order=travel_order)
display(travel)
rate_chart(travel, "BusinessTravel", "Attrition Rate by Business Travel (%)")

      BusinessTravel  Employees  Exited  AttritionRate  vs_Overall_pp
0         Non-Travel        150      12           8.00          -8.12
1      Travel Rarely       1043     156          14.96          -1.16
2  Travel Frequently        277      69          24.91           8.79

In [ ]:
df["DistanceBand"] = pd.cut(df["DistanceFromHome"], bins=[0, 5, 10, 20, 100],
                            labels=["1-5 km", "6-10 km", "11-20 km", "21+ km"])
dist_order = ["1-5 km", "6-10 km", "11-20 km", "21+ km"]
dist = attr_table("DistanceBand", order=dist_order)
display(dist)
rate_chart(dist, "DistanceBand", "Attrition Rate by Distance From Home (%)")

  DistanceBand  Employees  Exited  AttritionRate  vs_Overall_pp
0       1-5 km        632      87          13.77          -2.35
1      6-10 km        394      57          14.47          -1.65
2     11-20 km        240      48          20.00           3.88
3       21+ km        204      45          22.06           5.94

In [ ]:
combo = (df.groupby(["OverTime", "BusinessTravel"], observed=True)
           .agg(Employees=("Attrition", "size"), Exited=("Attrition", "sum"))
           .assign(AttritionRate=lambda x: (x.Exited / x.Employees * 100).round(2))
           .reset_index())
display(combo)

heat = (df.pivot_table(index="OverTime", columns="BusinessTravel",
                       values="Attrition", aggfunc="mean") * 100).round(1)
heat = heat[travel_order]

fig = px.imshow(heat, text_auto=True, color_continuous_scale="Reds", aspect="auto",
                title="Attrition Rate (%) by Overtime and Business Travel")
fig.show()

  OverTime     BusinessTravel  Employees  Exited  AttritionRate
0       No         Non-Travel        115       5           4.35
1       No  Travel Frequently        191      33          17.28
2       No      Travel Rarely        748      72           9.63
3      Yes         Non-Travel         35       7          20.00
4      Yes  Travel Frequently         86      36          41.86
5      Yes      Travel Rarely        295      84          28.47

In [ ]:
df["WorkloadExposure"] = (
    (df["OverTime"] == "Yes").astype(int) +
    (df["BusinessTravel"] == "Travel Frequently").astype(int)
).map({0: "Neither", 1: "One factor", 2: "Both (OT + frequent travel)"})

expo_order = ["Neither", "One factor", "Both (OT + frequent travel)"]
expo = attr_table("WorkloadExposure", order=expo_order)
expo["WAI"] = (expo.AttritionRate / rate * 100).round(0)
expo["Share_of_All_Exits_%"] = (expo.Exited / exited * 100).round(2)
display(expo)

fig = px.bar(expo, x="WorkloadExposure", y="WAI", text="WAI",
             color="WAI", color_continuous_scale="Reds",
             title="Workload Attrition Index (100 = overall baseline)")
fig.add_hline(y=100, line_dash="dash", line_color="black")
fig.show()

,WorkloadExposure,Employees,Exited,AttritionRate,vs_Overall_pp,WAI,Share_of_All_Exits_%
0,Neither,863,77,8.92,-7.20,55.0,32.49
1,One factor,521,124,23.80,7.68,148.0,52.32
2,Both (OT + frequent travel),86,36,41.86,25.74,260.0,15.19

In [ ]:
for col in ["OverTime", "BusinessTravel", "DistanceBand", "WorkloadExposure"]:
    chi2, p, _, _ = chi2_contingency(pd.crosstab(df[col], df["Attrition"]))
    verdict = "significant" if p < 0.05 else "not significant"
    print(f"{col:17s} chi2={chi2:6.2f}  p={p:.4f}  -> {verdict}")

OverTime          chi2= 87.56  p=0.0000  -> significant
BusinessTravel    chi2= 24.18  p=0.0000  -> significant
DistanceBand      chi2= 11.38  p=0.0098  -> significant
WorkloadExposure  chi2= 97.92  p=0.0000  -> significant

In [ ]:
chk = (df.assign(Early=np.where(df.YearsAtCompany <= 2, "Early (<=2 yrs)", "Later (>2 yrs)"))
         .groupby(["Early", "OverTime"])
         .agg(Employees=("Attrition", "size"), Exited=("Attrition", "sum"))
         .assign(AttritionRate=lambda x: (x.Exited / x.Employees * 100).round(2))
         .reset_index())
display(chk)

             Early OverTime  Employees  Exited  AttritionRate
0  Early (<=2 yrs)       No        238      49          20.59
1  Early (<=2 yrs)      Yes        104      53          50.96
2   Later (>2 yrs)       No        816      61           7.48
3   Later (>2 yrs)      Yes        312      74          23.72

In [ ]:
df.to_csv("cleaned_attrition.csv", index=False)
files.download("cleaned_attrition.csv")

In [ ]:
for name, t in [("OVERTIME", ot), ("TRAVEL", travel), ("DISTANCE", dist),
                ("OT x TRAVEL", combo), ("WORKLOAD INDEX", expo), ("TENURE CHECK", chk)]:
    print(f"\n--- {name} ---")
    print(t.to_string(index=False))

--- OVERTIME ---
OverTime  Employees  Exited  AttritionRate  vs_Overall_pp
     Yes        416     127          30.53          14.41
      No       1054     110          10.44          -5.68

--- TRAVEL ---
   BusinessTravel  Employees  Exited  AttritionRate  vs_Overall_pp
       Non-Travel        150      12           8.00          -8.12
    Travel Rarely       1043     156          14.96          -1.16
Travel Frequently        277      69          24.91           8.79

--- DISTANCE ---
DistanceBand  Employees  Exited  AttritionRate  vs_Overall_pp
      1-5 km        632      87          13.77          -2.35
     6-10 km        394      57          14.47          -1.65
    11-20 km        240      48          20.00           3.88
      21+ km        204      45          22.06           5.94

--- OT x TRAVEL ---
OverTime    BusinessTravel  Employees  Exited  AttritionRate
      No        Non-Travel        115       5           4.35
      No Travel Frequently        191      33          17.28
      No     Travel Rarely        748      72           9.63
     Yes        Non-Travel         35       7          20.00
     Yes Travel Frequently         86      36          41.86
     Yes     Travel Rarely        295      84          28.47

--- WORKLOAD INDEX ---
           WorkloadExposure  Employees  Exited  AttritionRate  vs_Overall_pp   WAI  Share_of_All_Exits_%
                    Neither        863      77           8.92          -7.20  55.0                 32.49
                 One factor        521     124          23.80           7.68 148.0                 52.32
Both (OT + frequent travel)         86      36          41.86          25.74 260.0                 15.19

--- TENURE CHECK ---
          Early OverTime  Employees  Exited  AttritionRate
Early (<=2 yrs)       No        238      49          20.59
Early (<=2 yrs)      Yes        104      53          50.96
 Later (>2 yrs)       No        816      61           7.48
 Later (>2 yrs)      Yes        312      74          23.72